VOLUNTEER, ADOPT, SUPPORT = 1, 2, 3

VOLUNTEER_NAME, VOLUNTEER_PHONE, VOLUNTEER_EMAIL, VOLUNTEER_REMARK = 4, 5, 6, 7

ADOPTER_PHONE, ADOPTER_NAME = 8, 9

CHOOSE_SUPPORT, SUPPORT_US, SUPPORT_BY_FINANCE, SUPPORT_BY_KINDS = 9, 10, 11, 12

EN, AMH = 13, 14
