VOLUNTEER, ADOPT, SUPPORT = 1, 2, 3

VOLUNTEER_NAME, VOLUNTEER_PHONE, VOLUNTEER_CHURCH = 4, 5, 6

ADOPTER_PHONE, ADOPTER_NAME = 7, 8

CHOOSE_SUPPORT, SUPPORT_US, SUPPORT_BY_FINANCE, SUPPORT_BY_KINDS = 9, 10, 11, 12
